config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get '/new', to: 'games#new'
  post '/score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    @letters = ("A".."Z").to_a

    letters_amount = rand(5..10)

    @randomletters = generate_random_letters(letters_amount)
  end

  def score
    @longestword = params[:longestword]
    # given letters must be used ❌
    @result = check_letters(@longestword)
    # correct letters but no English word ❌
    # correct letters and English word ✅

  end

  def generate_random_letters(amount)
    amount.times.map {@letters.sample}
  end


  def check_letters(word)
    word_letters = word.split.upcase

    if word_letters.include?(@randomletters)
      "Congratulations! #{word} is great!"
    else
      "Sorry but #{word} can't be built out of #{@randomletters}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<div class="col-6">
  <h1>New game</h1>
  <p><%= @randomletters.join(" ") %></p>

  <form action="/score" method="post" data-turbo="false">
    <label for="userinput">What is the longest word you can find?</label>
    <input type="text" name="longestword" id="userinput" value="<%= params[:longestword] %>">
    <button>Play</button>
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  </form>
  <%= link_to 'See result', score_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>